http:
  middlewares:
    secure-headers:
      headers:
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: true
        referrerPolicy: strict-origin-when-cross-origin
        permissionsPolicy: geolocation=(), microphone=(), camera=()
        customFrameOptionsValue: SAMEORIGIN
    internal-whitelist:
      ipAllowList:
        sourceRange:
        - 192.168.1.0/24
    esphome-headers:
      headers:
        customRequestHeaders:
          X-Real-IP: ''
          X-Forwarded-For: ''
          X-Forwarded-Proto: ''
    netbox-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Host: ''
    myspeed-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        customResponseHeaders:
          Cache-Control: "no-cache, no-store, must-revalidate"
          Pragma: "no-cache"
          Expires: "0"
