http:
  serversTransports:
    insecure-transport:
      insecureSkipVerify: true
  services:
    adguard-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.253:3000
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    adguard2-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.224:3000
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    uptime-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.132:3001
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    birdnet-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.80:8080
        healthCheck:
          path: /dashboard
          interval: 2m
          timeout: 15s
          followRedirects: true
    homeassistant-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.155:8123
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    influx-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.56:8086
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    myspeed-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.152:5216
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    omada-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.47:8043
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    pairdrop-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.97:3000
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    proxmox-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.137:8006
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    proxmox2-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.125:8006
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    pulse-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.122:7655
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    watchyourlan-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.195:8840
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    wiki-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.135:3000
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    esphome-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.169:6052
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    z2m-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.228:8099
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    zwave-js-ui-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.141:8091
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    netbox-service:
      loadBalancer:
        servers:
        - url: http://192.168.1.138
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    truenas-service:
      loadBalancer:
        serversTransport: insecure-transport
        servers:
        - url: https://192.168.1.98:443
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
    caddy-service:
      loadBalancer:
        servers:
        - url: http://localhost:2019
        healthCheck:
          path: /
          interval: 2m
          timeout: 10s
          followRedirects: true
